// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aunihxuahmcqtgvsvrxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1bmloeHVhaG1jcXRndnN2cnhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg0Nzc5MjYsImV4cCI6MjA5NDA1MzkyNn0.0LVsuJQyPBNG34PHytj2HRJ4T4E67Sg3Bnw0IXn5W-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});